// Code generated by Slice Machine. DO NOT EDIT.

import AllPeople from "./AllPeople/index.svelte";
import Member from "./Member/index.svelte";
import SquadPeople from "./SquadPeople/index.svelte";

export const components = {
  all_people: AllPeople,
  member: Member,
  squad_people: SquadPeople,
};
