// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type SquadMemberDocumentDataSlicesSlice = never;

/**
 * Content for Squad Member documents
 */
interface SquadMemberDocumentData {
  /**
   * Slice Zone field in *Squad Member*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_member.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadMemberDocumentDataSlicesSlice>;
}

/**
 * Squad Member document from Prismic
 *
 * - **API ID**: `squad_member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadMemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadMemberDocumentData>,
    "squad_member",
    Lang
  >;

type SquadPageDocumentDataSlicesSlice = SquadPeopleSlice;

/**
 * Content for squad documents
 */
interface SquadPageDocumentData {
  /**
   * Slice Zone field in *squad*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: squad_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *squad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: squad_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * squad document from Prismic
 *
 * - **API ID**: `squad_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadPageDocumentData>,
    "squad_page",
    Lang
  >;

export type AllDocumentTypes = SquadMemberDocument | SquadPageDocument;

/**
 * Primary content in *SquadPeople → Items*
 */
export interface SquadPeopleSliceDefaultItem {
  /**
   * Naam field in *SquadPeople → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_people.items[].naam
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  naam: prismic.RichTextField;

  /**
   * Afbeelding field in *SquadPeople → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_people.items[].afbeelding
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  afbeelding: prismic.ImageField<never>;
}

/**
 * Default variation for SquadPeople Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadPeopleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SquadPeopleSliceDefaultItem>
>;

/**
 * Slice variation for *SquadPeople*
 */
type SquadPeopleSliceVariation = SquadPeopleSliceDefault;

/**
 * SquadPeople Shared Slice
 *
 * - **API ID**: `squad_people`
 * - **Description**: SquadPeople
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadPeopleSlice = prismic.SharedSlice<
  "squad_people",
  SquadPeopleSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SquadMemberDocument,
      SquadMemberDocumentData,
      SquadMemberDocumentDataSlicesSlice,
      SquadPageDocument,
      SquadPageDocumentData,
      SquadPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      SquadPeopleSlice,
      SquadPeopleSliceDefaultItem,
      SquadPeopleSliceVariation,
      SquadPeopleSliceDefault,
    };
  }
}
